#ifndef HIKARI_RENDER_DESCRIPTOR_LAYOUT_INCLUDED
#define HIKARI_RENDER_DESCRIPTOR_LAYOUT_INCLUDED

#include "Include/Contracts/HIKARI_ShaderResourceBindings.hlsli"

static const uint HIKARI_RENDER_SYSTEM_SRV_DYNAMIC_BEGIN =
    HIKARI_SHADER_SYSTEM_SRV_DYNAMIC_BEGIN;
static const uint HIKARI_RENDER_SYSTEM_SRV_DYNAMIC_COUNT =
    HIKARI_SHADER_SYSTEM_SRV_DYNAMIC_COUNT;

#endif
