#ifndef HIKARI_RENDER_DESCRIPTOR_LAYOUT_INCLUDED
#define HIKARI_RENDER_DESCRIPTOR_LAYOUT_INCLUDED

static const uint HIKARI_RENDER_SYSTEM_SRV_DYNAMIC_BEGIN = 4001u;
static const uint HIKARI_RENDER_SYSTEM_SRV_DYNAMIC_COUNT = 111u;

#endif
